-- Add file_type column to files table
ALTER TABLE files ADD COLUMN file_type VARCHAR(50) AFTER filename;

-- Create application_data table
CREATE TABLE IF NOT EXISTS application_data (
    application_id VARCHAR(255) NOT NULL PRIMARY KEY,
    extracted_name VARCHAR(255),
    extracted_major VARCHAR(255),
    extracted_country VARCHAR(255),
    extracted_degree_level VARCHAR(255),
    extracted_course VARCHAR(255),
    prerequisite_required TINYINT(1),
    extracted_text TEXT,
    extracted_citizenship_status VARCHAR(255),
    extracted_field_of_study VARCHAR(255),
    extracted_program_format VARCHAR(255),
    student_status VARCHAR(50),
    field_of_study VARCHAR(50),
    program_format VARCHAR(50),
    start_semester VARCHAR(50),
    start_year VARCHAR(10),
    email VARCHAR(255),
    phone VARCHAR(50),
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    zip_code VARCHAR(20),
    country VARCHAR(100),
    is_us_resident TINYINT(1),
    citizen_type VARCHAR(50),
    military_service TINYINT(1),
    university VARCHAR(255),
    degree VARCHAR(100),
    major VARCHAR(255),
    gpa DECIMAL(3,2),
    campus VARCHAR(50),
    program VARCHAR(255),
    enrollment_semester VARCHAR(50),
    residency_status VARCHAR(50),
    is_international TINYINT(1),
    age INT,
    FOREIGN KEY (application_id) REFERENCES files(application_id)
); 